# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pepe/Desktop/UNIVERSIDAD/SEGUNDO/IS/Entrega_FInal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pepe/Desktop/UNIVERSIDAD/SEGUNDO/IS/Entrega_FInal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pepe/Desktop/UNIVERSIDAD/SEGUNDO/IS/Entrega_FInal/CMakeFiles /home/pepe/Desktop/UNIVERSIDAD/SEGUNDO/IS/Entrega_FInal/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pepe/Desktop/UNIVERSIDAD/SEGUNDO/IS/Entrega_FInal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TuProyecto_tests

# Build rule for target.
TuProyecto_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TuProyecto_tests
.PHONY : TuProyecto_tests

# fast build rule for target.
TuProyecto_tests/fast:
	$(MAKE) -f CMakeFiles/TuProyecto_tests.dir/build.make CMakeFiles/TuProyecto_tests.dir/build
.PHONY : TuProyecto_tests/fast

#=============================================================================
# Target rules for targets named TuProyecto

# Build rule for target.
TuProyecto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TuProyecto
.PHONY : TuProyecto

# fast build rule for target.
TuProyecto/fast:
	$(MAKE) -f CMakeFiles/TuProyecto.dir/build.make CMakeFiles/TuProyecto.dir/build
.PHONY : TuProyecto/fast

Tests.o: Tests.cpp.o

.PHONY : Tests.o

# target to build an object file
Tests.cpp.o:
	$(MAKE) -f CMakeFiles/TuProyecto_tests.dir/build.make CMakeFiles/TuProyecto_tests.dir/Tests.cpp.o
.PHONY : Tests.cpp.o

Tests.i: Tests.cpp.i

.PHONY : Tests.i

# target to preprocess a source file
Tests.cpp.i:
	$(MAKE) -f CMakeFiles/TuProyecto_tests.dir/build.make CMakeFiles/TuProyecto_tests.dir/Tests.cpp.i
.PHONY : Tests.cpp.i

Tests.s: Tests.cpp.s

.PHONY : Tests.s

# target to generate assembly for a file
Tests.cpp.s:
	$(MAKE) -f CMakeFiles/TuProyecto_tests.dir/build.make CMakeFiles/TuProyecto_tests.dir/Tests.cpp.s
.PHONY : Tests.cpp.s

Usuario.o: Usuario.cpp.o

.PHONY : Usuario.o

# target to build an object file
Usuario.cpp.o:
	$(MAKE) -f CMakeFiles/TuProyecto_tests.dir/build.make CMakeFiles/TuProyecto_tests.dir/Usuario.cpp.o
	$(MAKE) -f CMakeFiles/TuProyecto.dir/build.make CMakeFiles/TuProyecto.dir/Usuario.cpp.o
.PHONY : Usuario.cpp.o

Usuario.i: Usuario.cpp.i

.PHONY : Usuario.i

# target to preprocess a source file
Usuario.cpp.i:
	$(MAKE) -f CMakeFiles/TuProyecto_tests.dir/build.make CMakeFiles/TuProyecto_tests.dir/Usuario.cpp.i
	$(MAKE) -f CMakeFiles/TuProyecto.dir/build.make CMakeFiles/TuProyecto.dir/Usuario.cpp.i
.PHONY : Usuario.cpp.i

Usuario.s: Usuario.cpp.s

.PHONY : Usuario.s

# target to generate assembly for a file
Usuario.cpp.s:
	$(MAKE) -f CMakeFiles/TuProyecto_tests.dir/build.make CMakeFiles/TuProyecto_tests.dir/Usuario.cpp.s
	$(MAKE) -f CMakeFiles/TuProyecto.dir/build.make CMakeFiles/TuProyecto.dir/Usuario.cpp.s
.PHONY : Usuario.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/TuProyecto.dir/build.make CMakeFiles/TuProyecto.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/TuProyecto.dir/build.make CMakeFiles/TuProyecto.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/TuProyecto.dir/build.make CMakeFiles/TuProyecto.dir/main.cpp.s
.PHONY : main.cpp.s

menu.o: menu.cpp.o

.PHONY : menu.o

# target to build an object file
menu.cpp.o:
	$(MAKE) -f CMakeFiles/TuProyecto.dir/build.make CMakeFiles/TuProyecto.dir/menu.cpp.o
.PHONY : menu.cpp.o

menu.i: menu.cpp.i

.PHONY : menu.i

# target to preprocess a source file
menu.cpp.i:
	$(MAKE) -f CMakeFiles/TuProyecto.dir/build.make CMakeFiles/TuProyecto.dir/menu.cpp.i
.PHONY : menu.cpp.i

menu.s: menu.cpp.s

.PHONY : menu.s

# target to generate assembly for a file
menu.cpp.s:
	$(MAKE) -f CMakeFiles/TuProyecto.dir/build.make CMakeFiles/TuProyecto.dir/menu.cpp.s
.PHONY : menu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TuProyecto_tests"
	@echo "... TuProyecto"
	@echo "... Tests.o"
	@echo "... Tests.i"
	@echo "... Tests.s"
	@echo "... Usuario.o"
	@echo "... Usuario.i"
	@echo "... Usuario.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... menu.o"
	@echo "... menu.i"
	@echo "... menu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

